name: Deploy do Site Estático para GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  pages: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout do Código
        uses: actions/checkout@v4

      - name: 2. Configurar o GitHub Pages
        uses: actions/configure-pages@v5

      - name: 3. Upload dos Artefatos Estáticos
        uses: actions/upload-pages-artifact@v3
        with:
          path: './'

      - name: 4. Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
